server:
  shutdown: "graceful"

spring:
  cloud:
    config:
      override-none: true
      allow-override: true
      override-system-properties: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
  kafka:
    logging:
      enabled: true

logging:
  level:
    root: INFO
    id.co.bni.maverick: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    reactor.netty.http.client: DEBUG
  pattern:
    level: "%5p [appName=${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"
